succeeds {
  function add(x,y) :: int, int -> int {
    return x+y;
  }
}
{
  if (add(10,12) != 22) {
    throw "epic fail";
  }
};

blames "client" {
  function add(x,y) :: int, int -> int {
    return x+y;
  }
}
{
  add("ten","eleven");
};

blames "chocolate" {
  function foo() :: -> int {
    throw "chocolate violated the contract; haha funny";
    return 12;
  }
}
{
  foo();
};
